version: "3"
services:

  redis:
    image: "redis:alpine"
    container_name: "redis"

  todo:
    container_name: "todo"
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - redis
      - postgres
   

  postgres:
    image: "postgres"
    container_name: "postgres"
    restart: "always"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  
volumes:
  data:
    