version: "3"
services:

  redis:
    image: "redis:alpine"
    container_name: "redis"

  todo:
    container_name: "todo"
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - redis
  
 